---
title: "R Notebook"
output: html_notebook
---

__Name:__

__Student ID:__

For each of the exercises below, take advantage of R markdown and the notebook features.  That is include the code and have Rstudio embed your answers.  See Exercise 0 for an example


## Exercise 0 (example)
_Provide the name of your current working directory and list the files therein_
```{r}
getwd()
dir()
```

(You would then click on the > arrow in your answer code block to run it before continuing)

## Exercise 1
_Use sum() to determine the sum of numbers from 2000 to 20000.  Provide your code and the actual sum in your answer._


## Exercise 2
_In one or two sentences, describe what the above code snippet it did._

## Exercise 3
_Add the contents of a and b together and place the results in a new object.  Examine the result.  Include your code.  Try using both `sum()` and `+`; do you get different results?  If so, why?_

## Exercise 4
_What is the sum of the 5th through 10th element of object b?  Provide your code and the sum._

## Exercise 5
_What is the sum of the 3rd, 8th, and 10th element of b?  For both of these exercises should only need to have "b" in your code once._


## Exercise 6
_When extracting from a 2-dimensional object, which number specifies rows and which specifies columns?_

_What does `m[3,]` do?_

_How can you extract the 3rd, 4th and 5th columns of m together as one object?_

## Exercise 7
_What does the cbind command do?  How about rbind?_

_Create a new object "n" where the first row is a new row of numbers (your choice) and the following rows are the followed by the m matrix._

_Want more? (OPTIONAL) do the same but reverse the order of the rows from m._


## Exercise 8

_How many hits have an e-value of 0?_

_How many have hits have a percent identity > 50?_

_Recalculate the above values but in percentage of hits rather than absolute values._

_How many hits have an E-value of 0 and have a percent identity less than 50?_

_What is the minimum percent identity of the hits with an E-value equal to 0?_

## Excercise 9
_Are you surprised that sequences with relatively low percent identity can still have an E-value of 0?_

_State a hypothesis about what alignment properties might produce a zero E-value even when the percent identity is less than 50%._

_Test your hypothesis_

## Excercise 10
_It sometimes is useful to create a random subset of a large data set like the fly.worm results.  Create a new dataframe `fly.worm.small` that has 1,000 rows taken at random from the larger data set._

## Exercise 11
_Use the `summary()` and `head()` functions to examine the stereotypes object._

_Record the answers to the "activity break sections" from Ciera's visualiztio tutorial here:_ 

## Exercise 12
_Use ggplot to explore the relationship between score ("Score") and alignment length("len").  Provide a plot that illustrates the relationship and describe the relationship in words._

## Excercise 13
_While you might expect that BLAST results with long alignments would have high scores, this is not always the case.  Form a hypothesis as to what might influence the relationship between alignment length and score.  Use ggplot to make a new plot to explore this hypothesis.  Does the plot support your hypothesis or not?  State your hypothesis, provide the code for your plot, and state your conclusion._

** Turning in the assignment**

* Click the "Preview" Button to generate an up-to-date html version of your notebook.  Check it to make sure you are happy with its content.
* add your .Rmd and .nb.html files to the repository and commit the changes.
* push the changes
